'use client'

import { useState } from 'react'
import Topbar from '../components/Topbar'
import { FileText, Download, Calendar, Activity, ShieldCheck, PieChart, TrendingDown, Clock, Zap, AlertTriangle, FileOutput, CheckCircle2, X } from 'lucide-react'
import { toPng } from 'html-to-image'
import { jsPDF } from 'jspdf'

export default function Reports() {
  const [activeTab, setActiveTab] = useState<'rca' | 'compliance' | 'capex' | 'efficiency'>('rca')
  const [pdfModalOpen, setPdfModalOpen] = useState(false)
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false)

  const handleSavePDF = async () => {
    const element = document.getElementById('pdf-content')
    if (!element) return

    try {
      setIsGeneratingPdf(true)
      const dataUrl = await toPng(element, { cacheBust: true, pixelRatio: 2 })
      
      const pdf = new jsPDF('p', 'mm', 'a4')
      const pdfWidth = pdf.internal.pageSize.getWidth()
      const pdfHeight = (element.offsetHeight * pdfWidth) / element.offsetWidth
      
      pdf.addImage(dataUrl, 'PNG', 0, 0, pdfWidth, pdfHeight)
      pdf.save('GridGuard_RCA_Report.pdf')
    } catch (error) {
      console.error('Error generating PDF', error)
      alert('Failed to generate PDF. Please try again.')
    } finally {
      setIsGeneratingPdf(false)
    }
  }

  return (
    <main className="main-area">
      <Topbar />
      <div className="content h-full flex flex-col">
        <div className="page-heading mb-6">
          <div>
            <div className="eyebrow">GRIDGUARD <span>/</span> REPORTS</div>
            <h1>Reports & Analytics</h1>
            <p>Generate, export, and schedule AI-driven operational reports.</p>
          </div>
          <div className="heading-actions">
            <button className="button">
              <Calendar size={14} /> Schedule Exports
            </button>
            <button className="button primary">
              <Download size={14} /> Export All (PDF)
            </button>
          </div>
        </div>

        {/* Custom Tab Navigation (using existing CSS patterns) */}
        <div className="flex border-b border-[#273543] mb-6">
          {[
            { id: 'rca', label: 'Post-Incident (RCA)', icon: AlertTriangle },
            { id: 'compliance', label: 'Compliance & Audits', icon: ShieldCheck },
            { id: 'capex', label: 'Asset & CapEx', icon: PieChart },
            { id: 'efficiency', label: 'Grid Efficiency', icon: Activity }
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`flex items-center gap-2 px-6 py-3 border-b-2 text-xs font-bold tracking-wider uppercase transition-colors ${
                activeTab === tab.id
                  ? 'border-[#e7ad54] text-[#e7ad54]'
                  : 'border-transparent text-[#748697] hover:text-[#aeb9c3]'
              }`}
            >
              <tab.icon size={14} />
              {tab.label}
            </button>
          ))}
        </div>

        <div className="flex-1 overflow-auto">
          {activeTab === 'rca' && (
            <div className="animate-fade-in-up">
              <div className="panel mb-6">
                <div className="panel-head">
                  <h2>Recent Root Cause Analyses</h2>
                  <div className="panel-actions">
                    <div className="search">
                      <input type="text" placeholder="Search incidents..." />
                    </div>
                  </div>
                </div>
                <div className="p-6">
                  <div className="border border-[#273543] rounded bg-[#0d151e] p-5 mb-4 relative overflow-hidden glass-card">
                    <div className="absolute top-0 left-0 w-1 h-full bg-[#e05b59]"></div>
                    <div className="flex justify-between items-start mb-4">
                      <div>
                        <div className="text-[#8896a5] text-xs font-mono mb-1">INC-2026-09-12-A</div>
                        <h3 className="text-lg font-bold text-white mb-2">Substation B Transformer Cascading Failure</h3>
                        <p className="text-sm text-[#748697] max-w-3xl">
                          Automated RCA generated by ML-Service (Confidence: 94%). The outage was triggered by a rapid degradation of insulating oil in TX-1002, exacerbated by unexpected peak load from the Industrial Zone.
                        </p>
                      </div>
                      <button className="button small" onClick={() => setPdfModalOpen(true)}><FileOutput size={12}/> View Full PDF</button>
                    </div>
                    <div className="grid grid-cols-3 gap-4 mt-4 pt-4 border-t border-[#273543]">
                      <div>
                        <strong className="block text-[#e7ad54] text-xs mb-1">Primary Root Cause</strong>
                        <span className="text-[#aeb9c3] text-sm">Thermal runaway (Insulation breakdown)</span>
                      </div>
                      <div>
                        <strong className="block text-[#e7ad54] text-xs mb-1">Preventable?</strong>
                        <span className="text-[#5fc299] text-sm flex items-center gap-1"><CheckCircle2 size={12}/> Yes (Missed Alert)</span>
                      </div>
                      <div>
                        <strong className="block text-[#e7ad54] text-xs mb-1">Recommended Mitigation</strong>
                        <span className="text-[#aeb9c3] text-sm">Deploy DGA sensors to Substation B.</span>
                      </div>
                    </div>
                  </div>

                  <div className="border border-[#273543] rounded bg-[#0d151e] p-5 relative overflow-hidden opacity-70 hover:opacity-100 transition-opacity">
                    <div className="absolute top-0 left-0 w-1 h-full bg-[#e7ad54]"></div>
                    <div className="flex justify-between items-start mb-4">
                      <div>
                        <div className="text-[#8896a5] text-xs font-mono mb-1">INC-2026-08-30-B</div>
                        <h3 className="text-lg font-bold text-white mb-2">Solar Array 1 Inverter Sync Loss</h3>
                        <p className="text-sm text-[#748697] max-w-3xl">
                          Inverter synchronization failure due to transient voltage spikes from the main grid interconnect.
                        </p>
                      </div>
                      <button className="button small" onClick={() => setPdfModalOpen(true)}><FileOutput size={12}/> View Full PDF</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'compliance' && (
            <div className="animate-fade-in-up">
              <div className="grid grid-cols-2 gap-6 mb-6">
                <div className="panel">
                  <div className="panel-head">
                    <h2>NERC CIP Compliance</h2>
                    <button className="button small">Generate</button>
                  </div>
                  <div className="p-6">
                    <div className="flex items-center justify-between mb-4 border-b border-[#273543] pb-4">
                      <div>
                        <strong className="block text-white text-sm">Cyber Security Audit</strong>
                        <span className="text-[#748697] text-xs">Last run: Today 08:00 AM</span>
                      </div>
                      <div className="badge badge-green">100% PASS</div>
                    </div>
                    <div className="flex items-center justify-between">
                      <div>
                        <strong className="block text-white text-sm">Physical Security Perimeter</strong>
                        <span className="text-[#748697] text-xs">Last run: Yesterday</span>
                      </div>
                      <div className="badge badge-amber">1 WARNING</div>
                    </div>
                  </div>
                </div>
                <div className="panel">
                  <div className="panel-head">
                    <h2>FERC Uptime Standards</h2>
                    <button className="button small">Generate</button>
                  </div>
                  <div className="p-6">
                    <div className="kpi-value text-[#5fc299]">99.998%</div>
                    <div className="text-xs text-[#8896a5] mt-1 mb-4">SAIDI: 1.2 hours / SAIFI: 0.8 interruptions</div>
                    <p className="text-sm text-[#748697]">
                      GridGuard operations exceed regional FERC reliability mandates for the current fiscal quarter. 
                      Automated ML load shedding prevented 3 major cascaded outages.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'capex' && (
            <div className="animate-fade-in-up">
              <div className="panel mb-6">
                <div className="panel-head">
                  <h2>End of Life & Depreciation Forecast</h2>
                  <div className="panel-actions">
                     <select>
                      <option>Next 12 Months</option>
                      <option>Next 3 Years</option>
                      <option>Next 5 Years</option>
                    </select>
                  </div>
                </div>
                <div className="table-wrap">
                  <table>
                    <thead>
                      <tr>
                        <th>ASSET ID</th>
                        <th>LOCATION</th>
                        <th>INSTALL DATE</th>
                        <th>AI HEALTH SCORE</th>
                        <th>EST. REPLACEMENT COST</th>
                        <th>CAPEX PRIORITY</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>
                          <div className="asset-name">
                            <div className="risk-dot critical"></div>
                            <div>
                              <strong>TX-1001</strong>
                              <span>Step-down Transformer</span>
                            </div>
                          </div>
                        </td>
                        <td>Valley Region</td>
                        <td>1998-04-12</td>
                        <td>
                          <div className="health-cell">
                            <div className="health-bar"><i className="red" style={{ width: '15%' }}></i></div>
                            <b className="text-red">15%</b>
                          </div>
                        </td>
                        <td className="font-mono">$2.4M</td>
                        <td><div className="badge badge-red">CRITICAL (Q1)</div></td>
                      </tr>
                      <tr>
                        <td>
                          <div className="asset-name">
                            <div className="risk-dot high"></div>
                            <div>
                              <strong>TX-1021</strong>
                              <span>Distribution Transformer</span>
                            </div>
                          </div>
                        </td>
                        <td>Industrial Zone</td>
                        <td>2005-11-03</td>
                        <td>
                          <div className="health-cell">
                            <div className="health-bar"><i className="amber" style={{ width: '42%' }}></i></div>
                            <b className="text-amber">42%</b>
                          </div>
                        </td>
                        <td className="font-mono">$1.1M</td>
                        <td><div className="badge badge-amber">MEDIUM (Q3)</div></td>
                      </tr>
                      <tr>
                        <td>
                          <div className="asset-name">
                            <div className="risk-dot low"></div>
                            <div>
                              <strong>SW-4402</strong>
                              <span>Substation Switchgear</span>
                            </div>
                          </div>
                        </td>
                        <td>Substation A</td>
                        <td>2018-02-15</td>
                        <td>
                          <div className="health-cell">
                            <div className="health-bar"><i className="green" style={{ width: '85%' }}></i></div>
                            <b className="text-green">85%</b>
                          </div>
                        </td>
                        <td className="font-mono">$450K</td>
                        <td><div className="badge badge-green">LOW (2029)</div></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'efficiency' && (
            <div className="animate-fade-in-up">
              <div className="grid grid-cols-3 gap-6 mb-6">
                <div className="panel p-6 border-t-4 border-t-[#6e9ed0]">
                  <div className="flex items-center gap-3 mb-2">
                    <Zap className="text-[#6e9ed0]" size={20} />
                    <h3 className="font-bold text-white m-0">Renewables Integration</h3>
                  </div>
                  <div className="text-3xl font-bold text-white mt-4">34.2%</div>
                  <div className="text-xs text-[#5fc299] flex items-center gap-1 mt-1"><TrendingDown size={12}/> +4.1% vs last month</div>
                  <p className="text-xs text-[#748697] mt-4">Total grid load powered by Solar Array 1 and Wind Farm Alpha.</p>
                </div>
                
                <div className="panel p-6 border-t-4 border-t-[#e7ad54]">
                  <div className="flex items-center gap-3 mb-2">
                    <TrendingDown className="text-[#e7ad54]" size={20} />
                    <h3 className="font-bold text-white m-0">Transmission Loss</h3>
                  </div>
                  <div className="text-3xl font-bold text-white mt-4">4.8%</div>
                  <div className="text-xs text-[#e05b59] flex items-center gap-1 mt-1"><Activity size={12}/> +0.2% vs last month</div>
                  <p className="text-xs text-[#748697] mt-4">Energy lost during transmission. Increase correlated with heatwave.</p>
                </div>

                <div className="panel p-6 border-t-4 border-t-[#5fc299]">
                  <div className="flex items-center gap-3 mb-2">
                    <Clock className="text-[#5fc299]" size={20} />
                    <h3 className="font-bold text-white m-0">Peak Load Shifting</h3>
                  </div>
                  <div className="text-3xl font-bold text-white mt-4">12.5 MW</div>
                  <div className="text-xs text-[#5fc299] flex items-center gap-1 mt-1"><CheckCircle2 size={12}/> Optimized via AI</div>
                  <p className="text-xs text-[#748697] mt-4">Megawatts successfully deferred from peak pricing periods.</p>
                </div>
              </div>
            </div>
          )}

        </div>
      </div>

      {pdfModalOpen && (
        <div className="modal-backdrop">
          <div className="modal compact" style={{ width: '800px', height: '85vh', display: 'flex', flexDirection: 'column' }}>
            <div className="modal-head mb-4 border-b border-[#273543] pb-4">
              <div>
                <h2>GridGuard Automated RCA Report</h2>
                <div className="text-xs text-[#748697] mt-1">Generated: 2026-09-12 14:02:44 UTC</div>
              </div>
              <div className="flex gap-2">
                <button 
                  className="button small primary" 
                  onClick={handleSavePDF} 
                  disabled={isGeneratingPdf}
                >
                  <Download size={12} /> {isGeneratingPdf ? 'Generating...' : 'Save PDF'}
                </button>
                <button className="icon-btn" onClick={() => setPdfModalOpen(false)}><X size={20} /></button>
              </div>
            </div>
            
            {/* Simulated PDF Viewer Content */}
            <div className="flex-1 overflow-y-auto overflow-x-hidden bg-[#e5e7eb] py-8 px-4 rounded border border-[#273543] custom-scrollbar">
              <div className="flex justify-center w-full">
                {/* PDF Document "Paper" */}
                <div id="pdf-content" className="bg-white w-full max-w-[700px] h-fit min-h-[850px] p-12 shadow-2xl text-[#1a202c] font-sans relative mb-8">
                
                {/* PDF Top Accent */}
                <div className="absolute top-0 left-0 right-0 h-2 bg-[#0c141d]"></div>
                
                {/* PDF Header */}
                <div className="border-b-2 border-[#e7ad54] pb-6 mb-8 flex justify-between items-start mt-2">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-[#0c141d] text-[#e7ad54] flex items-center justify-center rounded">
                      <Zap size={24} />
                    </div>
                    <div>
                      <div className="text-2xl font-black tracking-tight text-[#0c141d]">GRIDGUARD</div>
                      <div className="text-[10px] font-bold text-[#748697] tracking-widest uppercase mt-1">Operations Platform</div>
                    </div>
                  </div>
                  <div className="text-right">
                    <div className="text-xs font-bold text-[#e05b59] border border-[#e05b59] px-2 py-1 rounded inline-block mb-2">CONFIDENTIAL / INTERNAL</div>
                    <div className="text-xs text-[#748697]">Document ID: <strong className="text-[#0c141d]">RCA-INC-2026-09-12-A</strong></div>
                    <div className="text-xs text-[#748697]">Generated: <strong className="text-[#0c141d]">2026-09-12 14:02:44 UTC</strong></div>
                  </div>
                </div>

                {/* PDF Title */}
                <div className="text-center mb-10">
                  <h1 className="text-2xl font-bold text-[#0c141d] mb-2 uppercase tracking-wide">Root Cause Analysis Report</h1>
                  <h2 className="text-base text-[#748697]">Incident: Substation B Cascading Failure</h2>
                </div>
                
                {/* PDF Body */}
                <div className="space-y-8">
                  <section>
                    <h3 className="text-sm font-bold text-[#0c141d] uppercase tracking-wider border-b border-gray-200 pb-2 mb-4 flex items-center gap-2">
                      <div className="w-2 h-2 bg-[#e7ad54]"></div>
                      1. Executive Summary
                    </h3>
                    <p className="text-sm leading-relaxed text-gray-700">
                      At 14:00 UTC on Sept 12, 2026, an unexpected cascading failure occurred originating from Substation B. 
                      GridGuard's automated ML-Service has determined with <strong className="text-[#0c141d] bg-yellow-100 px-1">94% confidence</strong> that the primary root cause 
                      was a rapid degradation of insulating oil inside Step-Down Transformer TX-1002. This was exacerbated by an unexpected peak 
                      load surge from the adjacent Industrial Zone.
                    </p>
                  </section>

                  <section>
                    <h3 className="text-sm font-bold text-[#0c141d] uppercase tracking-wider border-b border-gray-200 pb-2 mb-4 flex items-center gap-2">
                      <div className="w-2 h-2 bg-[#e7ad54]"></div>
                      2. Timeline of Events
                    </h3>
                    <div className="relative border-l-2 border-gray-200 ml-3 pl-6 space-y-4">
                      <div className="relative">
                        <div className="absolute -left-[31px] top-1 w-3 h-3 bg-gray-300 rounded-full border-2 border-white"></div>
                        <strong className="text-sm text-[#0c141d]">13:45 UTC:</strong>
                        <span className="text-sm text-gray-700 ml-2">Minor voltage fluctuations detected by secondary sensors.</span>
                      </div>
                      <div className="relative">
                        <div className="absolute -left-[31px] top-1 w-3 h-3 bg-yellow-400 rounded-full border-2 border-white"></div>
                        <strong className="text-sm text-[#0c141d]">13:52 UTC:</strong>
                        <span className="text-sm text-gray-700 ml-2">ML-Service flagged anomalous thermal signature.</span>
                      </div>
                      <div className="relative">
                        <div className="absolute -left-[31px] top-1 w-3 h-3 bg-orange-500 rounded-full border-2 border-white"></div>
                        <strong className="text-sm text-[#0c141d]">13:58 UTC:</strong>
                        <span className="text-sm text-gray-700 ml-2">Substation B primary relay tripped.</span>
                      </div>
                      <div className="relative">
                        <div className="absolute -left-[31px] top-1 w-3 h-3 bg-red-600 rounded-full border-2 border-white"></div>
                        <strong className="text-sm text-[#0c141d]">14:00 UTC:</strong>
                        <span className="text-sm text-gray-700 ml-2">TX-1002 experienced critical thermal runaway.</span>
                      </div>
                    </div>
                  </section>

                  <section>
                    <h3 className="text-sm font-bold text-[#0c141d] uppercase tracking-wider border-b border-gray-200 pb-2 mb-4 flex items-center gap-2">
                      <div className="w-2 h-2 bg-[#e7ad54]"></div>
                      3. Mitigation & Recommendations
                    </h3>
                    <p className="text-sm leading-relaxed text-gray-700 mb-4">
                      The AI models indicate this incident was fully preventable had Dissolved Gas Analysis (DGA) sensors been active. 
                      Immediate recommendations:
                    </p>
                    <div className="border-l-4 border-[#e05b59] bg-red-50 p-4 text-sm text-red-900 rounded-r">
                      <div className="font-bold flex items-center gap-2 mb-1"><AlertTriangle size={16} /> ACTION REQUIRED</div>
                      Deploy real-time DGA sensory equipment to all step-down transformers at Substation B and C immediately. Schedule expedited maintenance for adjacent transformer units.
                    </div>
                  </section>
                </div>

                {/* PDF Footer / Sign-off */}
                <div className="mt-16 pt-6 border-t border-gray-200 grid grid-cols-2 text-sm">
                  <div>
                    <div className="text-gray-400 italic mb-6">Digitally Signed By:</div>
                    <div className="font-mono text-[#0c141d] font-bold border-b border-gray-300 inline-block pb-1 mb-1">GRIDGUARD AI (ML-v0.8)</div>
                    <div className="text-xs text-gray-500 uppercase tracking-wide">Authorized Operations Intelligence</div>
                  </div>
                  <div className="text-right flex flex-col items-end">
                     <div className="text-gray-400 italic mb-6">Reviewed By:</div>
                     <div className="border-b border-gray-300 w-40 pb-1 mb-1"></div>
                     <div className="text-xs text-gray-500 uppercase tracking-wide">Operations Manager</div>
                  </div>
                </div>

              </div>
              </div>
            </div>
          </div>
        </div>
      )}

    </main>
  )
}
